name: Continuous Integration
on:
  push:
    branches:
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest  # または特定のバージョン例: 1.1.0

      - name: Install dependencies
        run: bun install

      - name: Lint
        run: bun run lint

      - name: Format
        run: bun run format

      - name: Typecheck
        run: bun run typecheck